# Generated by Django 3.2.25 on 2025-02-22 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('published_date', 'title')},
        ),
    ]
